### ISSUE TITLE
Post-Processing of measures

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#39]
All data stored in database are in the 3857 (Spherical Mercator projection) coordinate system. (measures, buildings etc)

The precision loss are negligible far from poles. 
Post-Processing steps:

TODO

**Comment by nicolas-f** [comment]
@ebocher @gpetit What is the error in Finland of Spherical Mercator projection ?

**Comment by ebocher** [comment]
Many major online street mapping services (Bing Maps, OpenStreetMap, Google Maps, MapQuest, Yahoo! Maps, and others) use a variant of the Mercator projection for their map images[8] called Web Mercator or Google Web Mercator. Despite its obvious scale variation at small scales, the projection is well-suited as an interactive world map that can be zoomed seamlessly to large-scale (local) maps, where there is relatively little distortion due to the variant projection's near-conformality.

The major online street mapping services tiling systems display most of the world at the lowest zoom level as a single square image, excluding the polar regions by truncation at latitudes of φmax = ±85.05113°. (See below.) Latitude values outside this range are mapped using a different relationship that doesn't diverge at φ = ±90°.

More information on  https://en.wikipedia.org/wiki/Mercator_projection#Truncation_and_aspect_ratio

**Comment by ebocher** [comment]
And this one http://mappemonde.mgm.fr/num20/internet/int08401.html

**Comment by nicolas-f** [comment]
Regular mesh with 3857 (Spherical Mercator projection) coordinate system
Circle are reference 25m circumference (local projection), hexagon is 25m circumference in epsg 3857.

Equator:
![transequat](https://cloud.githubusercontent.com/assets/1382241/17173509/8b90eff8-53fb-11e6-9f99-73c257039016.png)

Nantes:
![transnantes](https://cloud.githubusercontent.com/assets/1382241/17173519/9728e8a2-53fb-11e6-8313-b4cc8520b373.png)

North Finland:
![transfinlande](https://cloud.githubusercontent.com/assets/1382241/17173523/9fd5da64-53fb-11e6-91af-e18d29712818.png)

**Comment by nicolas-f** [comment]
Fixed: Was an error in javascript code

**Comment by Picaut** [comment]
@nicolas-f Can we closed this issue?

**Comment by nicolas-f** [comment]
yes

**Comment by Picaut** [comment]
Done
